### ISSUE TITLE
Use case: const bitflags

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/const-eval#47]
I'd like to be able to use [bitflags](https://crates.io/crates/bitflags) as the value of a `const`:

```rust
const MY_FLAGS: SomeFlags = SomeFlags::A | SomeFlags::B;
```

This produces an error saying that `calls in constants are limited to constant functions, tuple structs and tuple variants`.

What would be the blockers for making bitflags operations work as the value of a `const`?

**Comment by jplatte** [comment]
As written, this requires `const fn` in traits (https://github.com/rust-lang/rfcs/pull/2632). There is an implementation based on that at https://github.com/bitflags/bitflags/pull/217.

As a workaround, this could be done on stable today with `const` inherent methods instead of operators:

```rust
const MY_FLAGS: SomeFlags = SomeFlags::A.or(SomeFlags::B);
```

**Comment by joshtriplett** [comment]
@jplatte `.or` looks reasonable to me; thanks!

In the meantime, if there's already an issue tracking const handling in traits, feel free to close this in favor of such an issue. Might be worth noting this as a use case in the skill-tree graph, though.

**Comment by RalfJung** [comment]
There's no tracking issue yet because the RFC has not been finalized yet. Closing in favor of https://github.com/rust-lang/rfcs/pull/2632.
