### ISSUE TITLE
Link to skill tree

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/const-eval#51]
Somewhere in our md files we should have a link to https://rust-lang.github.io/const-eval/. maybe from the "skill tree" item in the ToC?

**Comment by oli-obk** [comment]
we can also render all of our md stuff with `mdbook` and just like from the main readme to the rendered version.

**Comment by RalfJung** [comment]
We could but that would be much more work... and then suddenly we have two URLs for the same document, which I think is rather confusing.
